#!/bin/bash

set -e

PLATFORM=arm

while [ -n "$1" ]; do
    case "$1" in
        --arm)
            PLATFORM=arm
            ;;
        --x86_64)
            PLATFORM=x86_64
            ;;
        *)
            echo "Unrecognized argument: $1" 1>&2
            exit 1
            ;;
    esac
    shift
done

set -e -o pipefail

(
    mkdir -p downloads
    cd downloads

    if [ $PLATFORM = arm ]; then
        rm -rf debian-tmp
        mkdir -p debian-tmp
        docker create --name mender-takeover-tmp arm32v7/debian
        docker cp -a mender-takeover-tmp:/ debian-tmp/
        docker rm mender-takeover-tmp
        ( cd debian-tmp && tar --owner=root --group=root -czf ../debian-arm.tar.gz . )
        rm -rf debian-tmp

        curl -z busybox-arm -o busybox-arm https://www.busybox.net/downloads/binaries/1.26.2-defconfig-multiarch/busybox-armv6l
    else
        rm -rf debian-tmp
        mkdir -p debian-tmp
        docker create --name mender-takeover-tmp debian
        docker cp -a mender-takeover-tmp:/ debian-tmp/
        docker rm mender-takeover-tmp
        ( cd debian-tmp && tar --owner=root --group=root -czf ../debian-x86_64.tar.gz . )
        rm -rf debian-tmp

        curl -z busybox-x86_64 -o busybox-x86_64 https://www.busybox.net/downloads/binaries/1.26.2-defconfig-multiarch/busybox-x86_64
    fi

    chmod ugo+x busybox-*
)

(
    rm -rf payload
    mkdir -p payload
    cd payload

    cp ../downloads/debian-$PLATFORM.tar.gz debian.tar.gz

    mkdir -p takeover.sh
    # Explicitly use wildcard to omit .git directory.
    cp ../takeover.sh/* takeover.sh

    if [ $PLATFORM = arm ]; then
        arm-linux-gnueabihf-gcc -static takeover.sh/fakeinit.c -o takeover.sh/fakeinit
    else
        gcc -static takeover.sh/fakeinit.c -o takeover.sh/fakeinit
    fi

    # Unfortunately minimal Debian installs don't come with mkfs.vfat, so we
    # need to build the whole image here and include that instead.
    dd if=/dev/zero of=boot-part.vfat bs=1M seek=16 count=0
    mkfs.vfat -n Boot boot-part.vfat
    rm -rf tmp
    mkdir -p tmp
    (
        cd tmp
        tar xzf ../../downloads/grub-efi-$PLATFORM.tar.gz
    )
    mcopy -i boot-part.vfat -s tmp/* ::/
    rm -rf tmp
    gzip boot-part.vfat

    (
        cd takeover.sh

        mv ../boot-part.vfat.gz .
        cp ../../downloads/busybox-$PLATFORM busybox

        for patch in ../../patches/*.patch; do
            patch -p1 --batch --no-backup-if-mismatch < $patch
        done
        cp ../../mender-takeover.sh .
        echo 'exec /bin/bash /mender-takeover.sh' >> takeover.sh

        tar --owner=root --group=root -czf ../takeover.sh.tar.gz .
    )

    rm -rf takeover.sh
)

mender-artifact write module-image -T mender-takeover -f payload/debian.tar.gz -f payload/takeover.sh.tar
