#!/bin/bash

set -e

WORKDIR="$2"

prepare_takeover() {
    mkdir -p /takeover
    mount tmpfs /takeover -t tmpfs
    cd /takeover

    tar xzf $WORKDIR/debian.tar.gz
    tar xzf $WORKDIR/takeover.sh.tar.gz
}

do_takeover() {
    cd /takeover
    if [ -n "$(which systemd-run)" ]; then
        systemd-run bash -c "cd /takeover && exec ./takeover.sh $(tty)"
    else
        exec ./takeover.sh
    fi
}

case "$1" in
    ArtifactInstall)
        prepare_takeover
        ;;

    NeedsArtifactReboot)
        echo "Yes"
        ;;

    ArtifactReboot)
        # We need to do most of the work in ArtifactReboot, because it is the
        # only state where we are allowed to kill the mender daemon, which we
        # need to do.
        # TODO REMOVE
        prepare_takeover
        do_takeover
        ;;

    ArtifactRollback)
        if [ -e "$WORKDIR/too-late-to-roll-back" ]; then
            exit 1
        fi
        ;;

    Cleanup)
        rm -rf /takeover
        ;;

    *)
        :
        ;;
esac

