#!/bin/bash

set -e

WORKDIR="$2"

prepare_takeover() {
    umount -l /takeover || true
    rm -rf /takeover

    mkdir -p /takeover
    mount tmpfs /takeover -t tmpfs
    cd /takeover

    tar xzf $WORKDIR/files/debian.tar.gz
    tar xzf $WORKDIR/files/takeover.sh.tar.gz
}

do_takeover() {
    cd /takeover
    if [ -n "$(which systemd-run)" ]; then
        systemd-run bash -c "cd /takeover && exec ./takeover.sh $(tty)"
    else
        exec ./takeover.sh
    fi
}

case "$1" in
    SupportsRollback)
        echo "Yes"
        ;;

    ArtifactInstall)
        prepare_takeover
        ;;

    NeedsArtifactReboot)
        echo "Yes"
        ;;

    ArtifactReboot)
        # We need to do most of the work in ArtifactReboot, because it is the
        # only state where we are allowed to kill the mender daemon, which we
        # need to do.
        do_takeover
        # Should never get here
        echo "Returned from takeover without having taken over the device!"
        exit 1
        ;;

    ArtifactRollback)
        if [ -e /var/lib/mender/mender-takeover-too-late-to-roll-back ]; then
            exit 1
        fi
        ;;

    ArtifactVerifyReboot|ArtifactCommit)
        if [ ! -e /var/lib/mender/mender-takeover-finished ]; then
            echo "Did not complete all steps"
            exit 1
        fi
        ;;

    Cleanup)
        umount -l /takeover || true
        rm -rf /takeover
        ;;

    *)
        :
        ;;
esac

exit 0
