#!/bin/bash

set -e

WORKDIR="$2"

if [ -f $WORKDIR/files/env.sh ]; then
    source $WORKDIR/files/env.sh
fi

load_modules() {
    # This is needed for the VFAT partition we will mount later, and we can't
    # load modules after we have killed the original filesystem.
    /sbin/modprobe nls_ascii || true
    /sbin/modprobe nls_cp437 || true
}

install_packages() {
    apt update

    # The U-Boot tools conflict with the tools from grub-mender-grubenv.
    env DEBIAN_FRONTEND=noninteractive apt autoremove -yy u-boot-tools

    # grub-common is needed to get grub-editenv.
    env DEBIAN_FRONTEND=noninteractive apt install -yy grub-common
}

prepare_takeover() {
    umount -l /takeover || true
    rm -rf /takeover

    mkdir -p /takeover
    mount tmpfs /takeover -t tmpfs
    cd /takeover

    tar xzf $WORKDIR/files/debian.tar.gz
    tar xzf $WORKDIR/files/takeover.sh.tar.gz
}

do_takeover() {
    cd /takeover

    if [ -z "$DEBUG_TTY" ]; then
        if tty -s; then
            DEBUG_TTY="$(tty)"
        else
            DEBUG_TTY=/dev/tty1
        fi
    fi

    if [ -n "$(which systemd-run)" ]; then
        systemd-run bash -c "cd /takeover && exec ./takeover.sh $DEBUG_TTY"

        # Sleep for some time. 60 seconds should be enough to kill everything,
        # including this script.
        sleep 60
    else
        exec ./takeover.sh $DEBUG_TTY
    fi
}

case "$1" in
    SupportsRollback)
        echo "Yes"
        ;;

    ArtifactInstall)
        set -x
        load_modules
        install_packages
        prepare_takeover
        ;;

    NeedsArtifactReboot)
        echo "Yes"
        ;;

    ArtifactReboot)
        set -x
        # We need to do most of the work in ArtifactReboot, because it is the
        # only state where we are allowed to kill the mender daemon, which we
        # need to do.
        do_takeover
        # Should never get here
        echo "Returned from takeover without having taken over the device!"
        exit 1
        ;;

    ArtifactRollback)
        if [ -e /var/lib/mender/dual-rootfs-repartition-too-late-to-roll-back ]; then
            exit 1
        fi
        ;;

    ArtifactVerifyReboot|ArtifactCommit)
        if [ ! -e /var/lib/mender/dual-rootfs-repartition-finished ]; then
            echo "Did not complete all steps"
            exit 1
        fi
        ;;

    Cleanup)
        umount -l /takeover || true
        rm -rf /takeover
        ;;

    *)
        :
        ;;
esac

exit 0
